services:
  db:
    image: postgres:16-alpine
    container_name: library-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5434:5432"
    volumes:
      - library_db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: library-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/library?schema=public
      NODE_ENV: production
      PORT: 5174
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5174:5174"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: library-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  library_db-data:
